services:
  cache:
    image: redis:7.2-rc3-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass REDIS_PASSWORD
    volumes:
      - ./storage/cache:/storage

  cockroach1:
    image: cockroachdb/cockroach:v24.2.3-fips
    container_name: cockroach1
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --join=cockroach1,cockroach2,cockroach3 --advertise-addr=cockroach1 --listen-addr=0.0.0.0
    volumes:
     - ./storage/cockroach1:/cockroach/cockroach-data

  cockroach2:
    image: cockroachdb/cockroach:v24.2.3-fips
    container_name: cockroach2
    command: start --insecure --join=cockroach1,cockroach2,cockroach3 --advertise-addr=cockroach2 --listen-addr=0.0.0.0
    volumes:
     - ./storage/cockroach2:/cockroach/cockroach-data
    depends_on:
      - cockroach1
  
  cockroach3:
    image: cockroachdb/cockroach:v24.2.3-fips
    container_name: cockroach3
    command: start --insecure --join=cockroach1,cockroach2,cockroach3 --advertise-addr=cockroach2 --listen-addr=0.0.0.0
    volumes:
     - ./storage/cockroach3:/cockroach/cockroach-data
    depends_on:
      - cockroach1

volumes:
  cache:
    driver: local
  cockroach1:
    external: false
  cockroach2:
    external: false
  cockroach3:
    external: false